# Generated by Django 4.1.2 on 2022-12-05 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aspire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starred', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='folder',
            name='Recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipeId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddField(
            model_name='recipe_user',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspire.folder'),
        ),
        migrations.AddField(
            model_name='recipe_user',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspire.recipe'),
        ),
        migrations.AddField(
            model_name='recipe_user',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aspire.user'),
        ),
    ]
