# Generated by Django 4.1.2 on 2022-12-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aspire', '0008_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_user',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
